(() => {
  "use strict";
  const $ = (id) => document.getElementById(id);
  const el = {
    fileInput:$("fileInput"), folderInput:$("folderInput"), dropZone:$("dropZone"), clearButton:$("clearButton"), buildButton:$("buildButton"), downloadButton:$("downloadButton"),
    fileSummary:$("fileSummary"),fileCount:$("fileCount"),fileSize:$("fileSize"),fileList:$("fileList"),excludeExtensions:$("excludeExtensions"),excludeFailed:$("excludeFailed"),hideCounts:$("hideCounts"),excludeLowVolumeModes:$("excludeLowVolumeModes"),
    locationSelector:$("locationSelector"),locationSelectionCount:$("locationSelectionCount"),locationSearch:$("locationSearch"),selectAllLocations:$("selectAllLocations"),locationList:$("locationList"),
    progressCard:$("progressCard"),progressBar:$("progressBar"),statusPercent:$("statusPercent"),statusTitle:$("statusTitle"),statusMessage:$("statusMessage"),resultsCard:$("resultsCard"),resultsDescription:$("resultsDescription"),statsGrid:$("statsGrid"),totalsBody:$("totalsBody"),warningDetails:$("warningDetails"),warningList:$("warningList")
  };
  let files=[],locations=[],selected=new Set(),blob=null,name="parking_price_analysis.xlsx",discoverWarnings=[],finding=false;

  function supported(file){return /\.(?:csv|txt|html?|htm)$/i.test(file.name);}
  function unique(input){const m=new Map();for(const f of input){if(!supported(f))continue;const k=`${f.webkitRelativePath||f.name}|${f.size}|${f.lastModified}`;m.set(k,f);}return [...m.values()].sort((a,b)=>(a.webkitRelativePath||a.name).localeCompare(b.webkitRelativePath||b.name));}
  function bytes(n){if(n<1024)return`${n} B`;if(n<1024**2)return`${(n/1024).toFixed(1)} KB`;return`${(n/1024**2).toFixed(1)} MB`;}
  function buildState(){el.buildButton.disabled=!files.length||finding||!selected.size;}
  function selectionState(){el.locationSelectionCount.textContent=`${selected.size} of ${locations.length} ${locations.length===1?"location":"locations"} selected`;el.selectAllLocations.checked=locations.length>0&&selected.size===locations.length;el.selectAllLocations.indeterminate=selected.size>0&&selected.size<locations.length;buildState();}
  function renderLocations(){const q=el.locationSearch.value.trim().toLowerCase(),shown=locations.filter(x=>x.toLowerCase().includes(q));if(!shown.length){const p=document.createElement("p");p.className="location-list-empty";p.textContent=locations.length?"No locations match your search.":"No locations were found.";el.locationList.replaceChildren(p);return;}el.locationList.replaceChildren(...shown.map((loc,i)=>{const label=document.createElement("label");label.className="location-choice";const cb=document.createElement("input");cb.type="checkbox";cb.checked=selected.has(loc);cb.id=`loc-${i}`;cb.addEventListener("change",()=>{cb.checked?selected.add(loc):selected.delete(loc);blob=null;el.resultsCard.hidden=true;selectionState();});const span=document.createElement("span");span.textContent=loc;label.append(cb,span);return label;}));}
  async function discover(){locations=[];selected=new Set();discoverWarnings=[];el.locationSearch.value="";el.locationSelector.hidden=!files.length;finding=files.length>0;buildState();if(!files.length){finding=false;selectionState();return;}el.locationList.innerHTML='<p class="location-list-empty">Finding locations…</p>';try{const r=await ParkingAnalysis.discoverLocations(files);locations=r.locations;selected=new Set(locations);discoverWarnings=r.warnings||[];}catch(e){discoverWarnings=[e.message||String(e)];}finally{finding=false;renderLocations();selectionState();}}
  async function setFiles(input){files=unique(input);blob=null;el.resultsCard.hidden=true;el.progressCard.hidden=true;el.clearButton.disabled=!files.length;el.fileSummary.hidden=!files.length;if(!files.length){el.fileList.replaceChildren();el.locationSelector.hidden=true;await discover();return;}el.fileCount.textContent=`${files.length} report ${files.length===1?"file":"files"} selected`;el.fileSize.textContent=bytes(files.reduce((s,f)=>s+f.size,0));el.fileList.replaceChildren(...files.slice(0,50).map(f=>{const li=document.createElement("li"),n=document.createElement("div"),s=document.createElement("span");n.textContent=f.webkitRelativePath||f.name;s.textContent=bytes(f.size);li.append(n,s);return li;}));if(files.length>50){const li=document.createElement("li");li.textContent=`…and ${files.length-50} more supported files`;el.fileList.append(li);}await discover();}
  function progress(p,title,msg){const n=Math.max(0,Math.min(100,Math.round(p)));el.progressCard.hidden=false;el.progressBar.style.width=`${n}%`;el.statusPercent.textContent=`${n}%`;el.statusTitle.textContent=title;el.statusMessage.textContent=msg;}
  function count(v){const n=Number(v);return Number.isFinite(n)?n.toLocaleString("en-US"):"0";}
  function card(v,l){const d=document.createElement("div");d.className="stat";const s=document.createElement("strong"),x=document.createElement("span");s.textContent=v;x.textContent=l;d.append(s,x);return d;}
  function show(analysis){const totals=analysis.monthlyTotals||[],stats=analysis.stats||{},locCount=new Set(totals.map(r=>r.Location)).size;el.resultsDescription.textContent=`${locCount} selected ${locCount===1?"location":"locations"} and ${totals.length} location-month summaries were added.`;el.statsGrid.replaceChildren(card(count(locCount),"Locations included"),card(count(stats.rowsAnalyzed),"Resolve tickets analyzed"),card(count(stats.safetyFilesRead),"Safety Park files read"),card(count(stats.safetyDaysUsed),"Safety Park days added"),card(count(stats.extensionsRemoved),"Resolve extensions removed"),card(count(stats.lowVolumeModeRowsExcluded),"Low-volume modes hidden"));el.totalsBody.replaceChildren(...totals.map(r=>{const tr=document.createElement("tr");[r.Location,`${r.Month} ${r.Year}`,count(r["Total Tickets"]),ParkingAnalysis.formatMoney(Number(r["Total Revenue"])||0),ParkingAnalysis.formatMoney(Number(r["Average Ticket"])||0)].forEach((v,i)=>{const td=document.createElement("td");td.textContent=v;if(i>=2)td.className="number";tr.append(td);});return tr;}));const warnings=[...discoverWarnings,...(analysis.warnings||[])];el.warningDetails.hidden=!warnings.length;el.warningList.replaceChildren(...warnings.map(w=>{const li=document.createElement("li");li.textContent=w;return li;}));el.resultsCard.hidden=false;el.resultsCard.scrollIntoView({behavior:"smooth",block:"start"});}
  async function build(){if(!files.length||!selected.size)return;el.buildButton.disabled=true;el.resultsCard.hidden=true;el.progressBar.style.background="";blob=null;try{const options={excludeExtensions:el.excludeExtensions.checked,excludeFailed:el.excludeFailed.checked,hideCounts:el.hideCounts.checked,excludeLowVolumeModes:el.excludeLowVolumeModes.checked,selectedLocations:[...selected]};progress(2,"Reading reports","Starting analysis.");const analysis=await ParkingAnalysis.analyzeFiles(files,options,p=>{let pct=5;if(p.phase==="read")pct=5+(p.completed/Math.max(p.total,1))*40;else if(p.phase==="clean")pct=50;else if(p.phase==="summarize")pct=58;progress(pct,"Analyzing reports",p.message);});blob=await ParkingWorkbook.buildWorkbook(analysis,options,p=>progress(62+(p.completed/Math.max(p.total,1))*34,"Building workbook",p.message));name=`parking_price_analysis_${new Date().toISOString().slice(0,10)}.xlsx`;progress(100,"Workbook ready","Download it, then upload to Google Drive and open with Google Sheets.");show(analysis);}catch(e){console.error(e);progress(100,"Could not build workbook",e.message||String(e));el.progressBar.style.background="#a4262c";}finally{buildState();}}
  function download(){if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function clear(){files=[];locations=[];selected=new Set();discoverWarnings=[];blob=null;el.fileInput.value="";el.folderInput.value="";el.locationSearch.value="";el.locationSelector.hidden=true;el.fileSummary.hidden=true;el.progressCard.hidden=true;el.resultsCard.hidden=true;el.clearButton.disabled=true;el.fileList.replaceChildren();el.locationList.replaceChildren();buildState();}
  el.fileInput.addEventListener("change",e=>void setFiles([...e.target.files]));el.folderInput.addEventListener("change",e=>void setFiles([...e.target.files]));el.clearButton.addEventListener("click",clear);el.buildButton.addEventListener("click",build);el.downloadButton.addEventListener("click",download);el.locationSearch.addEventListener("input",renderLocations);el.selectAllLocations.addEventListener("change",()=>{selected=el.selectAllLocations.checked?new Set(locations):new Set();blob=null;el.resultsCard.hidden=true;renderLocations();selectionState();});
  el.dropZone.addEventListener("click",e=>{if(!e.target.closest("label"))el.fileInput.click();});el.dropZone.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();el.fileInput.click();}});["dragenter","dragover"].forEach(n=>el.dropZone.addEventListener(n,e=>{e.preventDefault();el.dropZone.classList.add("is-dragging");}));["dragleave","drop"].forEach(n=>el.dropZone.addEventListener(n,e=>{e.preventDefault();el.dropZone.classList.remove("is-dragging");}));el.dropZone.addEventListener("drop",e=>void setFiles([...e.dataTransfer.files]));
})();
