(() => {
  "use strict";

  if (!window.ExcelJS || !window.ParkingWorkbook) return;

  const COLORS = { navy:"FF1F4E78", blue:"FF5B9BD5", paleBlue:"FFD9EAF7", headerBlue:"FFEAF2F8", green:"FFE2F0D9", red:"FFF4CCCC", border:"FFD9D9D9", white:"FFFFFFFF", dark:"FF1F1F1F", muted:"FF666666", tieBg:"FFFFF2CC", tieText:"FF9C6500" };
  const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
  const CHART_COLORS = ["#9DC3E6", "#C0504D", "#70AD47", "#8064A2", "#ED7D31", "#5B9BD5"];

  function fill(argb){return{type:"pattern",pattern:"solid",fgColor:{argb}};}
  function border(){const side={style:"thin",color:{argb:COLORS.border}};return{top:side,bottom:side,left:side,right:side};}
  function body(cell,align="left"){cell.border=border();cell.alignment={horizontal:align,vertical:"middle"};}
  function header(cell){cell.fill=fill(COLORS.headerBlue);cell.font={bold:true};cell.border=border();cell.alignment={horizontal:"center",vertical:"middle"};}
  function group(cell){cell.fill=fill(COLORS.blue);cell.font={bold:true,color:{argb:COLORS.white}};cell.border=border();cell.alignment={horizontal:"center",vertical:"middle"};}
  function title(cell){cell.fill=fill(COLORS.navy);cell.font={bold:true,color:{argb:COLORS.white},size:16};cell.alignment={horizontal:"center",vertical:"middle"};}
  function compactMoney(value){const n=Number(value);if(!Number.isFinite(n))return"";return Number.isInteger(n)?`$${n.toLocaleString("en-US")}`:`$${n.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
  function groupBy(items,keyFn){const map=new Map();for(const item of items||[]){const key=keyFn(item);if(!map.has(key))map.set(key,[]);map.get(key).push(item);}return map;}
  function safeSheetName(name,used){let base=String(name).replace(/\s+Parking\s*$/i,"").replace(/[\\/*?:\[\]]/g,"-").trim().slice(0,31)||"Location";let candidate=base,n=2;while(used.has(candidate.toLowerCase())){const s=` (${n++})`;candidate=`${base.slice(0,31-s.length)}${s}`;}used.add(candidate.toLowerCase());return candidate;}
  function durationSort(value){const text=String(value||"").trim();const m=text.match(/^(?:(\d+)h)?\s*(?:(\d+)\s*mins?)?$/i);if(m&&(m[1]||m[2]))return[0,Number(m[1]||0)*60+Number(m[2]||0),text.toLowerCase()];return[1,0,text.toLowerCase()];}
  function tupleCompare(a,b){for(let i=0;i<Math.max(a.length,b.length);i+=1){if(a[i]<b[i])return-1;if(a[i]>b[i])return 1;}return 0;}
  function monthlyLookup(rows){const m=new Map();for(const r of rows||[])m.set(`${r.Year}|${r["Month Number"]}`,r);return m;}

  function averageIncrease(totals,years){if(years.length<2)return null;const older=years[years.length-2],newer=years[years.length-1],lookup=monthlyLookup(totals),values=[];for(let month=1;month<=12;month+=1){const a=lookup.get(`${older}|${month}`)?.["Total Revenue"],b=lookup.get(`${newer}|${month}`)?.["Total Revenue"];if(Number.isFinite(a)&&a>0&&Number.isFinite(b))values.push((b-a)/a);}return values.length?values.reduce((s,v)=>s+v,0)/values.length:null;}

  function renderRevenueChart(location,totals,years,canvas){const ctx=canvas.getContext("2d");ctx.clearRect(0,0,canvas.width,canvas.height);const lookup=monthlyLookup(totals);const chart=new Chart(ctx,{type:"bar",data:{labels:MONTHS,datasets:years.map((year,index)=>({label:String(year),data:MONTHS.map((_,i)=>lookup.get(`${year}|${i+1}`)?.["Total Revenue"]??null),backgroundColor:CHART_COLORS[index%CHART_COLORS.length],borderWidth:0}))},options:{responsive:false,animation:false,devicePixelRatio:2,plugins:{legend:{display:true,position:"top",labels:{boxWidth:12,font:{size:10}}},title:{display:false,text:location}},scales:{x:{grid:{display:false},ticks:{maxRotation:48,minRotation:48,autoSkip:false,font:{size:8}},title:{display:true,text:"Month",font:{size:9}}},y:{beginAtZero:true,ticks:{font:{size:8},callback:v=>`$${Number(v).toLocaleString("en-US")}`},grid:{color:"#D9E1E8"}}}}});chart.update("none");const image=chart.toBase64Image("image/png",1);chart.destroy();return image;}

  function addSummary(workbook,totals,canvas){const ws=workbook.addWorksheet("Summary",{views:[{state:"frozen",xSplit:2,ySplit:1}]});const years=[...new Set(totals.map(r=>Number(r.Year)))].sort((a,b)=>a-b),byLocation=groupBy(totals,r=>r.Location),locations=[...byLocation.keys()].sort((a,b)=>a.localeCompare(b));ws.getColumn(1).width=28;ws.getColumn(2).width=14;ws.getCell(1,1).value="Location";ws.getCell(1,2).value="Month";for(const c of[ws.getCell(1,1),ws.getCell(1,2)]){c.fill=fill(COLORS.navy);c.font={bold:true,color:{argb:COLORS.white}};c.alignment={horizontal:"center"};}
    const yearColumns=new Map();let col=3;for(const year of years){yearColumns.set(year,{revenue:col,tickets:col+1,average:col+2});ws.getColumn(col).width=15;ws.getColumn(col+1).width=12;ws.getColumn(col+2).width=14;ws.getColumn(col+1).hidden=true;ws.getColumn(col+2).hidden=true;ws.getCell(1,col).value=`${year} Revenue`;ws.getCell(1,col+1).value=`${year} Tickets`;ws.getCell(1,col+2).value=`${year} Avg Ticket`;for(let c=col;c<=col+2;c+=1){ws.getCell(1,c).fill=fill(COLORS.navy);ws.getCell(1,c).font={bold:true,color:{argb:COLORS.white}};ws.getCell(1,c).alignment={horizontal:"center"};}col+=3;}const chartCol=col+1;for(let c=col;c<=chartCol+6;c+=1)ws.getColumn(c).width=c===col?2:12;
    let row=2;for(const location of locations){const locationTotals=byLocation.get(location),lookup=monthlyLookup(locationTotals),start=row;for(let month=1;month<=12;month+=1){ws.getCell(row,1).value=String(location).replace(/\s+Parking$/i,"");ws.getCell(row,2).value=MONTHS[month-1];body(ws.getCell(row,1));body(ws.getCell(row,2));if(month===1)ws.getCell(row,1).font={bold:true};let previousRevenue=null;for(const year of years){const cols=yearColumns.get(year),total=lookup.get(`${year}|${month}`),rc=ws.getCell(row,cols.revenue),tc=ws.getCell(row,cols.tickets),ac=ws.getCell(row,cols.average);body(rc,"right");body(tc,"right");body(ac,"right");if(total){rc.value=total["Total Revenue"];rc.numFmt="$#,##0.00";tc.value=total["Total Tickets"];ac.value=total["Average Ticket"];ac.numFmt="$#,##0.00";}else{rc.value="-";tc.value="-";ac.value="-";rc.alignment={horizontal:"center"};}if(previousRevenue!=null&&total&&total["Total Revenue"]<previousRevenue){rc.fill=fill(COLORS.red);const priorYear=years[years.indexOf(year)-1],priorCol=yearColumns.get(priorYear).revenue;ws.getCell(row,priorCol).fill=fill(COLORS.red);}previousRevenue=total?total["Total Revenue"]:null;}row+=1;}const image=renderRevenueChart(location,locationTotals,years,canvas),id=workbook.addImage({base64:image,extension:"png"});ws.addImage(id,{tl:{col:chartCol-1,row:start-1},ext:{width:390,height:220}});const avg=averageIncrease(locationTotals,years),avgRow=start+10;ws.getCell(avgRow,chartCol).value="Average Increase:";ws.getCell(avgRow,chartCol).font={bold:true};ws.getCell(avgRow,chartCol+2).value=avg==null?"-":avg;if(avg!=null)ws.getCell(avgRow,chartCol+2).numFmt="0.00%";row+=1;}ws.pageSetup={orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.2,right:.2,top:.3,bottom:.3,header:.1,footer:.1}};}

  function writeMode(cell,record){body(cell,"right");if(!record)return;if(record["Is Tie"]){cell.value=record["Mode Prices"].map(compactMoney).join(" / ");cell.fill=fill(COLORS.tieBg);cell.font={color:{argb:COLORS.tieText}};}else{cell.value=record["Most Common Price"];cell.numFmt="$0.##";}}

  function writeMonthBlock(ws,startRow,startCol,monthNumber,years,rows,totalsLookup,hideCounts){const groupWidth=1+years.length*2,gap=1,weekendStart=startCol+groupWidth+gap,endCol=weekendStart+groupWidth-1;ws.mergeCells(startRow,startCol,startRow,endCol);ws.getCell(startRow,startCol).value=MONTHS[monthNumber-1];ws.getCell(startRow,startCol).fill=fill(COLORS.paleBlue);ws.getCell(startRow,startCol).font={bold:true};ws.getCell(startRow,startCol).alignment={horizontal:"center"};ws.mergeCells(startRow+1,startCol,startRow+1,startCol+groupWidth-1);ws.getCell(startRow+1,startCol).value="Weekdays:";group(ws.getCell(startRow+1,startCol));ws.mergeCells(startRow+1,weekendStart,startRow+1,endCol);ws.getCell(startRow+1,weekendStart).value="Weekends";group(ws.getCell(startRow+1,weekendStart));
    function headers(baseCol){ws.getCell(startRow+2,baseCol).value="Duration";header(ws.getCell(startRow+2,baseCol));ws.getColumn(baseCol).width=18;years.forEach((year,i)=>{const pc=baseCol+1+i*2,cc=pc+1;ws.getCell(startRow+2,pc).value=`${year} Price`;ws.getCell(startRow+2,cc).value=`${year} Tickets`;header(ws.getCell(startRow+2,pc));header(ws.getCell(startRow+2,cc));ws.getColumn(pc).width=11;ws.getColumn(cc).width=12;ws.getColumn(cc).hidden=Boolean(hideCounts);});}headers(startCol);headers(weekendStart);ws.getColumn(startCol+groupWidth).width=2;
    const monthRows=rows.filter(r=>Number(r["Month Number"])===monthNumber),lookup=new Map(monthRows.map(r=>[`${r["Day Group"]}|${r.Year}|${r.Duration}`,r]));const durationsFor=g=>[...new Set(monthRows.filter(r=>r["Day Group"]===g).map(r=>r.Duration))].sort((a,b)=>tupleCompare(durationSort(a),durationSort(b)));const wd=durationsFor("Weekday"),we=durationsFor("Weekend"),maxRows=Math.max(wd.length,we.length,1);for(let i=0;i<maxRows;i+=1){const row=startRow+3+i;for(const[baseCol,groupName,durations]of[[startCol,"Weekday",wd],[weekendStart,"Weekend",we]]){const d=durations[i];body(ws.getCell(row,baseCol));if(d)ws.getCell(row,baseCol).value=d;years.forEach((year,y)=>{const pc=baseCol+1+y*2,cc=pc+1,rec=d?lookup.get(`${groupName}|${year}|${d}`):null;writeMode(ws.getCell(row,pc),rec);body(ws.getCell(row,cc),"right");if(rec){ws.getCell(row,cc).value=rec["Mode Count"];ws.getCell(row,cc).numFmt="0";}});}}let totalRow=startRow+3+maxRows;years.forEach((year,index)=>{const targetBase=index%2===0?startCol:weekendStart,tier=Math.floor(index/2),r=totalRow+tier,label=ws.getCell(r,targetBase),value=ws.getCell(r,targetBase+1+index*2);label.value=`${year} Total:`;label.font={bold:true};label.alignment={horizontal:"right"};const total=totalsLookup.get(`${year}|${monthNumber}`);value.value=total?total["Total Revenue"]:"-";value.font={bold:true};if(total)value.numFmt="$#,##0.00";else value.alignment={horizontal:"center"};const previous=index>0?totalsLookup.get(`${years[index-1]}|${monthNumber}`):null,comparison=previous&&total?(total["Total Revenue"]<previous["Total Revenue"]?COLORS.red:COLORS.green):COLORS.green;label.fill=fill(comparison);value.fill=fill(comparison);});return{endRow:totalRow+Math.max(1,Math.ceil(years.length/2))-1,endCol};}

  function addLocationSheet(workbook,location,summaryRows,totals,options,used){const ws=workbook.addWorksheet(safeSheetName(location,used)),years=[...new Set([...summaryRows.map(r=>Number(r.Year)),...totals.map(r=>Number(r.Year))])].sort((a,b)=>a-b),groupWidth=1+years.length*2,blockWidth=groupWidth*2+1,rightStart=1+blockWidth+2,finalCol=rightStart+blockWidth-1;ws.mergeCells(1,1,1,finalCol);ws.getCell(1,1).value=location;title(ws.getCell(1,1));ws.getRow(1).height=27;ws.mergeCells(2,1,2,finalCol);ws.getCell(2,1).value="Weekday and weekend prices are shown side by side. Ticket-count columns remain between yearly prices and are hidden by default. Monthly revenue totals are shown at the bottom of each month.";ws.getCell(2,1).font={italic:true,color:{argb:COLORS.muted},size:9};const totalsLookup=monthlyLookup(totals);let row=4;for(let pair=0;pair<6;pair+=1){const left=writeMonthBlock(ws,row,1,pair+1,years,summaryRows,totalsLookup,options.hideCounts),right=writeMonthBlock(ws,row,rightStart,pair+7,years,summaryRows,totalsLookup,options.hideCounts);row=Math.max(left.endRow,right.endRow)+2;}ws.pageSetup={orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.15,right:.15,top:.3,bottom:.3,header:.1,footer:.1}};ws.printTitlesRow="1:2";}

  function addSafetyDailySheet(workbook,rows){if(!rows?.length)return;const ws=workbook.addWorksheet("Safety Daily Prices");ws.state="hidden";const headers=["Date","Location","Price","Tickets Bought","Revenue","Types"];headers.forEach((h,i)=>{ws.getCell(1,i+1).value=h;header(ws.getCell(1,i+1));});rows.forEach((r,i)=>{const row=i+2;ws.getCell(row,1).value=r.Date;ws.getCell(row,1).numFmt="mm/dd/yyyy";ws.getCell(row,2).value=r.Location;ws.getCell(row,3).value=r.Price;ws.getCell(row,3).numFmt="$0.00";ws.getCell(row,4).value=r["Tickets Bought"];ws.getCell(row,5).value=r.Revenue;ws.getCell(row,5).numFmt="$#,##0.00";ws.getCell(row,6).value=r.Types;});[14,30,12,16,14,20].forEach((w,i)=>ws.getColumn(i+1).width=w);ws.views=[{state:"frozen",ySplit:1}];}

  async function buildWorkbook(analysis,options={},onProgress=()=>{}){if(!window.ExcelJS)throw new Error("ExcelJS did not load.");if(!window.Chart)throw new Error("Chart.js did not load.");const workbook=new ExcelJS.Workbook();workbook.creator="Safety Park Parking Price Report Builder";workbook.created=new Date();workbook.modified=new Date();const canvas=document.getElementById("chartCanvas");addSummary(workbook,analysis.monthlyTotals||[],canvas);const modes=groupBy(analysis.weekdayWeekend||[],r=>r.Location),totals=groupBy(analysis.monthlyTotals||[],r=>r.Location),locations=[...new Set([...modes.keys(),...totals.keys()])].sort((a,b)=>a.localeCompare(b)),used=new Set(["summary","safety daily prices"]);for(let i=0;i<locations.length;i+=1){const loc=locations[i];onProgress({completed:i,total:locations.length,message:`Formatting ${loc}`});addLocationSheet(workbook,loc,modes.get(loc)||[],totals.get(loc)||[],options,used);}addSafetyDailySheet(workbook,analysis.dailyPriceCounts||[]);onProgress({completed:locations.length,total:locations.length,message:"Writing workbook file"});const buffer=await workbook.xlsx.writeBuffer();return new Blob([buffer],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});}

  window.ParkingWorkbook.buildWorkbook=buildWorkbook;
})();
